### ISSUE TITLE
Change LLM model

### ISSUE THREAD

**Issue by Ar-ALN** [ElonMusk2002/Automated-Web-Scanner-with-AI-Integration#1]
Hi,
Actually want to change LLM model to Mixtral 7x8b API, maybe can you save me some time ? 

How can I easily change the LLM model ?

Thanks !

**Comment by ElonMusk2002** [comment]
Hi,

To transition from the LLM model to Mixtral 7x8b API, you'll need to update import statements, initialize the Mixtral API, adjust inference code, and thoroughly test. Could you clarify if you're seeking assistance with creating a pull request for this change?
